version: '3.8'

services:
  # --- BASES DE DONNÉES ---
  mongodb:
    image: mongo:6.0
    container_name: bdd_mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASS}
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - data_network

  postgresdb:
    image: postgres:15
    container_name: bdd_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASS}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    networks:
      - data_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  # --- SERVICE API (FastAPI) ---
  api:
    build:
      context: ./services
    container_name: app_api
    restart: unless-stopped
    depends_on:
      postgresdb:
        condition: service_healthy
      mongodb:
        condition: service_started
    ports:
      - "8000:8000"
    volumes:
      - uploads_data:/app/uploads
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASS=${POSTGRES_PASS}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=postgresdb
      - POSTGRES_PORT=5432
      - MONGO_USER=${MONGO_USER}
      - MONGO_PASS=${MONGO_PASS}
      - MONGO_HOST=mongodb
      - MONGO_PORT=27017
      - MONGO_DB=${MONGO_DB}
      - JWT_SECRET=${JWT_SECRET}
    networks:
      - data_network

  # --- GÉNÉRATEUR DE DONNÉES ---
  generateur_donnees:
    build:
      context: ./dataset
    container_name: app_generateur
    depends_on:
      - mongodb
      - postgresdb
    volumes:
      - ./dataset:/app
    profiles:
      - data_prep
    networks:
      - data_network
    environment:
      - MONGO_URI=mongodb://${MONGO_USER}:${MONGO_PASS}@mongodb:27017/
      - PG_URI=postgresql://${POSTGRES_USER}:${POSTGRES_PASS}@postgresdb:5432/${POSTGRES_DB}

# --- PERSISTANCE ET RÉSEAU ---
volumes:
  mongodb_data:
    name: hackathon_mongo_vol
  postgres_data:
    name: hackathon_pg_vol
  uploads_data:
    name: hackathon_uploads_vol

networks:
  data_network:
    name: hackathon_net
    driver: bridge
